version: '3'

services:
  authorizer:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: turingq-authorizer-dev
    restart: always
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - ${KEYCLOAK_PORT}:8080
    networks:
      - turingq-keycloak-net

  authorizer-config:
    image: quay.io/adorsys/keycloak-config-cli:latest-15.0.2
    container_name: turingq-authorizer-config-dev
    networks:
      - turingq-keycloak-net
    restart: always
    environment:
      KEYCLOAK_URL: http://turingq-authorizer-dev:8080/auth
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_SSLVERIFY: "false"
      IMPORT_PATH: /config
    volumes:
      - ./config/turingq.json:/config/turingq.json
    depends_on:
      - authorizer

networks:
  turingq-keycloak-net:
    driver: bridge
