kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: default
spec:
  type: NodePort
  # Mais uma vez, note que utilizamos um novo nodePort
  # para evitar conflitos
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: frontend
