apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizer-database-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: authorizer-database
  replicas: 1
  template:
    metadata:
      labels:
        app: authorizer-database
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: authorizer-database-configmap
          - secretRef:
              name: authorizer-database-secret
          name: authorizer-database
          image: postgres:13-alpine
