apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions-database-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: subscriptions-database
  replicas: 1
  template:
    metadata:
      labels:
        app: subscriptions-database
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: subscriptions-database-configmap
          - secretRef:
              name: subscriptions-database-secret
          name: subscriptions-database
          image: postgres:13-alpine
