apiVersion: batch/v1
kind: Job
metadata:
  name: authorizer-config-job
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: authorizer-config-configmap
        - secretRef:
            name: authorizer-config-secret
        name: authorizer-config
        image: ${REPO_HOST}/turingq-authorizer-config
      restartPolicy: OnFailure
