# Create a config-map.yml with the content below, uncomment the lines, and adjust the variable values as needed:

#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: ranking-configmap
#  namespace: default
#data:
#  PORT: '3003'
#  HOST: '0.0.0.0'
#  NODE_ENV: 'production'
#  PAGINATION_LIMIT: '10'
#  DB_CONNECTION: 'pg'
#  PG_HOST: 'ranking-database-service'
#  PG_PORT: '5432'
#  PG_DB_NAME: 'turingq-ranking'
#  RABBITMQ_CONNECTION_HOST: 'message-broker-service'
#  RABBITMQ_CONNECTION_PORT: '5672'
#  RABBITMQ_SUBSCRIPTIONS_EXCHANGE_NAME: 'turingq.subscriptions.exchange'
#  RABBITMQ_SUBSCRIPTIONS_RANKING_ANSWER_QUEUE_NAME: 'ranking.newanswer'
#  RABBITMQ_SUBSCRIPTIONS_RANKING_ANSWER_BINDING_NAME: 'count:answer'
#  RABBITMQ_SUBSCRIPTIONS_RANKING_QUESTION_QUEUE_NAME: 'ranking.newquestion'
#  RABBITMQ_SUBSCRIPTIONS_RANKING_QUESTION_BINDING_NAME: 'count:question'
