kind: Service
apiVersion: v1
metadata:
  name: ranking-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30006
  selector:
    app: ranking
